# Generated by Django 2.0.6 on 2018-07-07 07:18

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categoty',
            new_name='Category',
        ),
    ]
