# Generated by Django 2.0.6 on 2018-07-11 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_post_post_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_photo',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
