# Generated by Django 2.0.6 on 2018-07-12 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userinfo', '0008_auto_20180711_1526'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='nickname',
        ),
    ]
