# Generated by Django 2.0.6 on 2018-07-12 07:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0003_auto_20180704_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matching',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matchingpro.MatchingPro'),
        ),
    ]
